image: gitpod/workspace-dotnet

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build

ports:
  - port: 5276
    onOpen: notify
  - port: 7276
    onOpen: notify

vscode:
  extensions:
    - muhammad-sammy.csharp
